//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZONOproject.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainFormEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainFormEN() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZONOproject.Localization.MainFormEN", typeof(MainFormEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сollection title is too long.
        /// </summary>
        internal static string addingCollectionsLongNameContent {
            get {
                return ResourceManager.GetString("addingCollectionsLongNameContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention!.
        /// </summary>
        internal static string addingCollectionsLongNameTitle {
            get {
                return ResourceManager.GetString("addingCollectionsLongNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product added successfully!.
        /// </summary>
        internal static string addingProductContent {
            get {
                return ResourceManager.GetString("addingProductContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention!.
        /// </summary>
        internal static string addingProductTitle {
            get {
                return ResourceManager.GetString("addingProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter the collection name.
        /// </summary>
        internal static string addingSelectionEmptyDataFieldContent {
            get {
                return ResourceManager.GetString("addingSelectionEmptyDataFieldContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention!.
        /// </summary>
        internal static string addingSelectionEmptyDataFieldTitle {
            get {
                return ResourceManager.GetString("addingSelectionEmptyDataFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add collection.
        /// </summary>
        internal static string addNewCollectionButton {
            get {
                return ResourceManager.GetString("addNewCollectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add product.
        /// </summary>
        internal static string addNewProductButton {
            get {
                return ResourceManager.GetString("addNewProductButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The database is currently in use by another user, please try again later.
        /// </summary>
        internal static string databaseIsBusyContent {
            get {
                return ResourceManager.GetString("databaseIsBusyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention!.
        /// </summary>
        internal static string databaseIsBusyTitle {
            get {
                return ResourceManager.GetString("databaseIsBusyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error has occurred! Error code:.
        /// </summary>
        internal static string errorWhenWorkingWithDatabaseContent {
            get {
                return ResourceManager.GetString("errorWhenWorkingWithDatabaseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention!.
        /// </summary>
        internal static string errorWhenWorkingWithDatabaseTitle {
            get {
                return ResourceManager.GetString("errorWhenWorkingWithDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        internal static string exitButton {
            get {
                return ResourceManager.GetString("exitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to log out of your account?.
        /// </summary>
        internal static string exitMessageContent {
            get {
                return ResourceManager.GetString("exitMessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout.
        /// </summary>
        internal static string exitMessageTitle {
            get {
                return ResourceManager.GetString("exitMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Favorites.
        /// </summary>
        internal static string favoriteLabel {
            get {
                return ResourceManager.GetString("favoriteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Favorites.
        /// </summary>
        internal static string favoritesTitleLabel {
            get {
                return ResourceManager.GetString("favoritesTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filters.
        /// </summary>
        internal static string filtersButton {
            get {
                return ResourceManager.GetString("filtersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flag {
            get {
                object obj = ResourceManager.GetObject("flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter a name for the new collection.
        /// </summary>
        internal static string informationLabel {
            get {
                return ResourceManager.GetString("informationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load.
        /// </summary>
        internal static string loadProductPhotoButton {
            get {
                return ResourceManager.GetString("loadProductPhotoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ZONO - the best marketplace.
        /// </summary>
        internal static string MainForm {
            get {
                return ResourceManager.GetString("MainForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home page.
        /// </summary>
        internal static string mainPageLabel {
            get {
                return ResourceManager.GetString("mainPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home page.
        /// </summary>
        internal static string mainPageTitleLabel {
            get {
                return ResourceManager.GetString("mainPageTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rated, thanks for your feedback!.
        /// </summary>
        internal static string markSavedSuccessfullyContent {
            get {
                return ResourceManager.GetString("markSavedSuccessfullyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention!.
        /// </summary>
        internal static string markSavedSuccessfullyTitle {
            get {
                return ResourceManager.GetString("markSavedSuccessfullyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your mark.
        /// </summary>
        internal static string markTitle {
            get {
                return ResourceManager.GetString("markTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My selections.
        /// </summary>
        internal static string myCollectionsLabel {
            get {
                return ResourceManager.GetString("myCollectionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My selections.
        /// </summary>
        internal static string myCollectionsTitleLabel {
            get {
                return ResourceManager.GetString("myCollectionsTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My products.
        /// </summary>
        internal static string myProductsLabel {
            get {
                return ResourceManager.GetString("myProductsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My products.
        /// </summary>
        internal static string myProductsTitleLabel {
            get {
                return ResourceManager.GetString("myProductsTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a new collection.
        /// </summary>
        internal static string NewCollectionCreationForm {
            get {
                return ResourceManager.GetString("NewCollectionCreationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create/edit product.
        /// </summary>
        internal static string NewProductCreationForm {
            get {
                return ResourceManager.GetString("NewProductCreationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product card.
        /// </summary>
        internal static string ProductCardForm {
            get {
                return ResourceManager.GetString("ProductCardForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product color.
        /// </summary>
        internal static string productColorLabelTitle {
            get {
                return ResourceManager.GetString("productColorLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter product description.
        /// </summary>
        internal static string productDescriptionTextBox {
            get {
                return ResourceManager.GetString("productDescriptionTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manufacturer.
        /// </summary>
        internal static string productManufacturerLabelTitle {
            get {
                return ResourceManager.GetString("productManufacturerLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product mark.
        /// </summary>
        internal static string productMarkLabel {
            get {
                return ResourceManager.GetString("productMarkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter product name.
        /// </summary>
        internal static string productNameTextBox {
            get {
                return ResourceManager.GetString("productNameTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price.
        /// </summary>
        internal static string productPriceLabel {
            get {
                return ResourceManager.GetString("productPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product price.
        /// </summary>
        internal static string productPriceLabelTitle {
            get {
                return ResourceManager.GetString("productPriceLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product type.
        /// </summary>
        internal static string productTypeLabelTitle {
            get {
                return ResourceManager.GetString("productTypeLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Production year.
        /// </summary>
        internal static string productYearOfProductionLabelTitle {
            get {
                return ResourceManager.GetString("productYearOfProductionLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string saveMarkButton {
            get {
                return ResourceManager.GetString("saveMarkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string saveNewCollectionButton {
            get {
                return ResourceManager.GetString("saveNewCollectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search ....
        /// </summary>
        internal static string searchLineTextBox {
            get {
                return ResourceManager.GetString("searchLineTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collection added successfully.
        /// </summary>
        internal static string successfulCollectionCreationContent {
            get {
                return ResourceManager.GetString("successfulCollectionCreationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention!.
        /// </summary>
        internal static string successfulCollectionCreationTitle {
            get {
                return ResourceManager.GetString("successfulCollectionCreationTitle", resourceCulture);
            }
        }
    }
}
